---

- hosts: "{{ hosts_pattern | default('localhost') }}"
  gather_facts: True
  run_once: True
  pre_tasks:
    - name: Fail If Binary Provided Is Not Compiled For Host
      fail:
        msg:
          - "Binary not compiled for {{ ansible_system | lower }}."
          - 'Please provide correct archive.'
      when: ansible_system | lower not in binary_archive_url | lower

    - name: Fail If Project Path Does Not Exist
      block:
        - name: Terraform Project Path Does Not Exist
          stat:
            path: "{{ terraform_project_path }}"
          register: terraform_project_path_stat
          failed_when: not terraform_project_path_stat['stat']['exists']

  tasks:
    - name: Terraform Provisioning
      block:
        - name: Prepare Terrafrom Environment
          import_role:
            name: terraform_environment
            tasks_from: prepare

        - name: Execute Terraform Plan
          import_role:
            name: terraform_environment
            tasks_from: plan
      always:
        - name: Cleanup Terraform Environment
          import_role:
            name: terraform_environment
            tasks_from: cleanup
      rescue:
        - name: Notify Failure
          ansible.builtin.set_stats:
            data:
              ERROR:
                - "Validation failed."
                - "Failed to verify terraform plan."
                - "Please check playbook output for the exact error."
        - name: Failure
          fail:
            msg:
              - "Validation failed."
              - "Failed to verify terraform plan."
              - "Please check playbook output for the exact error."
