---

- name: "Terraform Action: '{{ terraform_plan_state }}' - Check Only: '{{ terraform_check_mode | default(False) }}'"
  environment:
    TF_CLI_ARGS: '-no-color'
    TF_IN_AUTOMATION: 'true'
  community.general.terraform:
    binary_path: "{{ terraform_binary_path }}"
    state: "{{ terraform_plan_state }}"
    variables: "{{ terraform_plan_variables | default(omit) }}"
    variables_files: "{{ terraform_plan_variables_files | default(omit) }}"
    backend_config: "{{ terraform_backend_config | default(omit) }}"
    backend_config_files: "{{ terraform_backend_config_files | default(omit) }}"
    force_init: True
    init_reconfigure: True
    project_path: "{{ terraform_project_path }}"
  check_mode: "{{ terraform_check_mode }}"
  register: terraform_plan_execution
